name: Deploy Beta

on:
  push:
    branches: [site]
  pull_request:
    branches: [site]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Beta

    steps:
      - name: Check if deployment requested
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '!deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Deploying to beta'
        if: github.event_name == 'pull_request' || steps.check.outputs.triggered == 'true'

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: lts

      - name: Install packages
        run: npm ci

      - name: Build and deploy
        run: npm run deploy:beta -- --token ${{ secrets.SURGE_TOKEN }}
