FROM nginx:mainline-alpine AS nginx
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./public/ /usr/share/nginx/html
RUN ln -sf /usr/share/nginx/html /usr/share/nginx/html/guides
EXPOSE 80
